version: 2
sources:
  - name: dtp_tpalermo
    description: dataset for demo class
    tables:
      - name: raw_gz_sales
        description: sales of gz

  - name: dtp_tpalermo
    description: dataset for demo class
    tables:
      - name: raw_gz_product
        description: producs of gz

  - name: dtp_tpalermo
    description: dataset for demo class
    tables:
      - name: raw_gz_ship
        description: ship of gz
